development: &default
  adapter: postgresql
  encoding: unicode
  database: sqily_development
  pool: 5
  username: postgres
  password:

test:
  <<: *default
  database: sqily_test

# USE DATABASE_URL environment variable for production
